languageCode = 'en-us'
title = "Val's Notes"
theme = 'fluency'
math = true
disableComment = true
author = 'Valerian'
summaryLength = 30
enableEmoji = true
publishDir = "docs"
baseURL = "https://vale979.github.io"

#menu
[menu]
    [[menu.main]]
        identifier = 'posts'
        name = 'Posts'
        url = 'posts/'
        weight = 1
    
    [[menu.main]]
        identifier = 'tags'
        name = 'Tags'
        url = 'tags/'
        weight = 2

    [[menu.main]]
        identifier = 'about'
        name = 'About Me'
        url = 'about/'
        weight = 3

#privacy stuff
[privacy]
    [privacy.disqus]
        disable =  true
    
    [privacy.googleAnalytics]
        anonymizeIP = true
        respectDoNotTrack = true

    [privacy.youtube]
        privacyEnhanced = true

[params]
    [params.assets]
        disableFingerprinting = true